### ISSUE TITLE
[Bug]: Not getting API key popup on launch

### ISSUE THREAD

**Issue by SpaghettDev** [es3n1n/ida-wakatime-py#4]
I have IDA v8.3 and on first install, I don't get the popup asking for the WakaTime API key.
I also don't have a `wakatime.cfg` file.
Console:
```
WakaTime > INFO > Loaded
WakaTime > INFO > v1.1 by @es3n1n, 2022
```

**Comment by SpaghettDev** [comment]
I realized the `wakatime.cfg` mentioned in the README.md is not one local to the IDA installation, but global.
Since I've already set up WakaTime for VSCode, it used that.
This could've been more clearer in the README.
Anyway sorry for this issue :p

**Comment by es3n1n** [comment]
Ah yes, I should definitely rewrite that part of readme. Sorry, I'm glad that you figured this out 😅
